### ISSUE TITLE
Stutter if run infinitely in parallel with RDR2 

### ISSUE THREAD

**Issue by watergun77** [morganleemiller/RDR2Volume#1]
On low performance machine, it will create stutter every 30secs as it loops infinitely in the background.

**Comment by morganleemiller** [comment]
are you experiencing a performance impact?

**Comment by watergun77** [comment]
Yes. It stops once I Alt-Tab and close the program. Alt-tab back to game, the "stutter" stops.

Anyway, I had made a little modification, and it is working fine now.

**Comment by morganleemiller** [comment]
closing issue
